export { default as Navbar } from '../Navbar/Navbar'
export { default as MainPage } from './MainPage'
export { default as Introduction } from './Introduction/Introduction'
export { default as RulesSection } from './RulesSection/RulesSection'
export { default as SymptomsSection } from './SymptomsSection/SymptomsSection'
export { default as AdditionalInfoSection } from './AdditionalInfoSection/AdditionalInfoSection'
export { default as LinksSection } from './LinksSection/LinksSection'