export { default as MainPage} from './MainPage/MainPage'
export { default as AboutPage} from './AboutPage/AboutPage'
export { default as ContactPage} from './ContactPage/ContactPage'
export { default as Navbar} from './Navbar/Navbar'
export { default as Footer} from './Footer/Footer'